name: Get stock recommendations (FMP -> LLM -> Supabase)

on:
  workflow_dispatch:
    inputs:
      stock_symbols:
        description: "Stock symbols"
        required: true
        default: "AAPL,GOOGL,MSFT"

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Log level: ${{ github.event.inputs.stock_symbols }}"
